import { sample } from 'rxjs';

export const initGrDetailPage = {
  listPerCodeView: [12, 13],
  listCodeShowIcon: [6, 8, 25, 27, 28],
};
export const initCharts = {
  line2Charts: ['BP'],
  lineCharts: ['O2S', 'BODY_TEMPER', 'PPI', 'PVi', 'WEIGHT', 'R2', 'HEIGHT'],
  barCharts: ['STEP', 'STEP_AZ'],
  isShowForMinute: ['HR', 'O2S', 'R2', 'PPI', 'PVi', 'BODY_TEMPER'],
  minMaxCharts: ['HR'],
  sampleTypeShowCharts: [
    'O2S',
    'HR',
    'R2',
    'PPI',
    'PVi',
    'BODY_TEMPER',
    'BP',
    'BLOOD_GLUCOSE',
    'WEIGHT',
    'PRV',
    'HR_VAR',
    'SpOC',
    'SpCO',
    'SpMet',
    'SpHb',
    'STEP_AZ',
    'STEP',
    'RRa',
    'RESTING_HR',
    'WALKING_HR_AVG',
    'HF_TREND',
    'AHAG',
    'HEIGHT',
  ],
  //monthNames: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
  monthNames: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  weekDays: ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'],
  listSharedSamples: [
    {
      sample_type_id: 'HR_Z',
      language_key: 'heartRateZones',
      body_type: 'avg',
      top_type: 'none',
      top_title: 'total',
    },
    {
      sample_type_id: 'HF_TREND',
      language_key: 'heartFitnessTrend',
      body_type: 'avg',
      top_type: 'none',
      top_title: 'trend',
    },
    {
      sample_type_id: 'AHAG',
      language_key: 'recommendedPhysicalActivity',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
    },
    {
      sample_type_id: 'STEP_AZ',
      language_key: 'activeSteps',
      body_type: 'avg',
      top_type: 'none',
      top_title: 'total',
    },
    {
      sample_type_id: 'HR',
      language_key: 'heartRate',
      body_type: 'list_value',
      top_type: 'min_max',
      top_title: '',
      last: false,
    },
    {
      sample_type_id: 'PR',
      language_key: 'pulseRate',
      body_type: 'list_value',
      top_type: 'min_max',
      top_title: '',
      last: false,
    },
    {
      sample_type_id: 'STEP',
      language_key: 'sampleTypeSteps',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
    },
    {
      sample_type_id: 'O2S',
      language_key: 'oxygenSaturation',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
    },
    {
      sample_type_id: 'PPI',
      language_key: 'peripheralPerfusionIndex',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'PVi',
      language_key: 'plethVariabilityIndex',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'R2',
      language_key: 'respirationRatePleth',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'BP',
      language_key: 'bloodPressure',
      body_type: 'avg',
      top_type: 'min_max',
      top_title: '',
      last: false,
    },
    {
      sample_type_id: 'RESTING_HR',
      language_key: 'restingHeartRate',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
    },
    {
      sample_type_id: 'HR_VAR',
      language_key: 'heartRateVariability',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
    },
    {
      sample_type_id: 'PRV',
      language_key: 'pulseRateVariability',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
    },
    {
      sample_type_id: 'WALKING_HR_AVG',
      language_key: 'walkingHeartRateAverage',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
    },
    {
      sample_type_id: 'BLOOD_GLUCOSE',
      language_key: 'bloodGlucose',
      body_type: 'last',
      top_type: 'min_max',
      top_title: '',
      last: false,
    },
    {
      sample_type_id: 'HEIGHT',
      language_key: 'height',
      body_type: 'last',
      top_type: 'last',
      top_title: '',
      last: true,
    },
    {
      sample_type_id: 'WEIGHT',
      language_key: 'weight',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
    },
    {
      sample_type_id: 'BMI',
      language_key: 'bodyMassIndex',
      body_type: 'avg',
      top_type: 'avg',
      top_title: '',
      last: false,
    },
    {
      sample_type_id: 'SLEEP_ANALYSIS',
      language_key: 'sleepAnalysis',
      body_type: 'list_value',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
    },
    {
      sample_type_id: 'SpCO',
      language_key: 'carboxyhemoglobin',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'SpOC',
      language_key: 'oxygenContent',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'SpHb',
      language_key: 'totalHemoglobin',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'RRa',
      language_key: 'respirationRateAcoustic',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'SpMet',
      language_key: 'methemoglobin',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: true,
    },
    {
      sample_type_id: 'BODY_TEMPER',
      language_key: 'bodyTemperature',
      body_type: 'avg',
      top_type: 'avg',
      top_title: 'avg',
      last: false,
      masimo: false,
    },
    {
      sample_type_id: 'SENSOR',
      language_key: 'sensor',
      body_type: 'total',
      top_type: 'none',
      top_title: '',
    },
  ],
};
